# Generated by Django 5.0.6 on 2024-06-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=255)),
                ('published', models.DateField(auto_now_add=True)),
                ('num_rooms', models.IntegerField(blank=True, default=0)),
                ('num_bathrooms', models.IntegerField(blank=True, default=1)),
                ('area', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('views', models.IntegerField(blank=True, default=0)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_flats', to='account.account')),
            ],
            options={
                'verbose_name': 'Flat',
                'verbose_name_plural': 'Flats',
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_view_count', to='flat.flat')),
            ],
        ),
    ]
