# Generated by Django 5.0.6 on 2024-06-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_flat_elevator_flat_renovated_alter_viewcount_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='flat',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
