# Generated by Django 5.0.6 on 2024-06-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_alter_flat_description_alter_flat_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='views',
        ),
        migrations.AddField(
            model_name='flat',
            name='view',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
