# Generated by Django 5.0.6 on 2024-06-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pending'), ('Terminado', 'Finished'), ('Aplazado', 'Posponed')], max_length=15)),
                ('task_date', models.DateField(auto_now_add=True)),
                ('task_limit_date', models.DateField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='account.account')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='flat.flat')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
