# Generated by Django 5.0.6 on 2024-06-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_options_remove_account_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ocupation',
            field=models.CharField(blank=True, choices=[('Estudiante', 'Student'), ('Trabajador', 'Worker')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='province_or_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
