# Generated by Django 5.0.6 on 2024-06-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='province_or_state',
        ),
    ]
