# Generated by Django 5.0.6 on 2024-06-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_rename_state_address_province_or_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='door',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='province_or_state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='via_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
