# Generated by Django 5.0.6 on 2024-06-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_status', models.CharField(choices=[('Aceptado', 'Accepted'), ('Rechazada', 'Rejected'), ('Pendiente', 'Pending')], max_length=20)),
                ('incident_date', models.DateField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_incidents', to='account.account')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.flat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_incidents', to='account.account')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
    ]
