# Generated by Django 5.0.6 on 2024-06-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='title',
            field=models.CharField(default='Temporary Default Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_status',
            field=models.CharField(choices=[('Aceptado', 'Accepted'), ('Rechazada', 'Rejected'), ('Pendiente', 'Pending')], default='Pendiente', max_length=20),
        ),
    ]
